// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV4yBgAEFs0UGM3mc16vw8aGV_MTEen34',
    appId: '1:1059275952186:android:03c4737fb623365f05a503',
    messagingSenderId: '1059275952186',
    projectId: 'flutter-varios-3c544',
    databaseURL: 'https://flutter-varios-3c544-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-3c544.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1IkzqgSpNNfuECPD1tIvtQ9Gkby8SZOA',
    appId: '1:1059275952186:ios:9947a4e8d63868a205a503',
    messagingSenderId: '1059275952186',
    projectId: 'flutter-varios-3c544',
    databaseURL: 'https://flutter-varios-3c544-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-3c544.appspot.com',
    iosClientId: '1059275952186-e0n4d35kclrmfgcup553tlnn5jk6sr5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifications',
  );
}
